In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3, 4, 5]

In [3]:
type(list1)

list

In [8]:
arr=np.array(list1)

In [10]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(0, 10)#create an array from 0 to 9  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
lst=list(range(0, 10)) #create a list from 0 to 9 
len(lst)

10

In [14]:
np.arange(0, 10, 2) #create an array from 0 to 9 with step 2
type(np.arange(0, 10, 2))

numpy.ndarray

In [15]:
np.zeros(5) #create an array of 5 zeros
np.zeros((3, 5)) #create a 3x5 matrix of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5) #create an array of 5 ones
np.ones((3, 5)) #create a 3x5 matrix of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#line space 
np.linspace(0, 10, 3) #create an array of 3 elements from 0 to 10
np.linspace(0, 10, 50) #create an array of 50 elements from 0 to 10
# line space gives different number of elements between the start and end points 

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
#2d array by line space 
np.linspace(0, 10, 50).reshape(5, 10)

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

In [21]:
#  reshape an array
arr = np.arange(0, 25)
arr.reshape(5, 5)
#convert it into 3d 
arr.reshape(5, 5).reshape(5, 5, 1)#convert it into 3d


array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [42]:
#create random numbers
np.random.randint(0, 100,9)#random number between 0 and 100

array([81, 73, 40, 68, 26, 29, 84, 38, 28], dtype=int32)

In [48]:
#convert it into 2d
np.random.randint(0,1,9).reshape(3, 3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [49]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.shape#shape of the array
type(arr)#type of the array
arr.dtype#data type of the array
arr.size#size of the array
arr.ndim#number of dimensions of the array

1

In [55]:
#convert array to 3d to 1d 
#flatten
arr.flatten()






array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
#ravel
arr.ravel()
arr.ravel().shape

(25,)

In [60]:
#create 2d list
list_2d=[[1,2,3],[4,5,6],[7,8,9]]
list_2d


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [65]:
arr=np.array(list_2d)

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr.shape

(3, 3)

In [ ]:
#change the shape of the array
arr.reshape(9, 1)
#change the shape  of the array


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [73]:
arr.T#transpose of the array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [74]:
arr=np.arange(60)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

# slicing 


In [76]:
arr[2]

np.int64(2)

In [77]:
arr[10]

np.int64(10)

In [78]:
arr[3:10:2]

array([3, 5, 7, 9])

In [79]:
arr[10:70]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [81]:
arr=np.arange(60)


In [85]:
# convert it into 2d
ar=arr.reshape(6, 10)



In [86]:
ar[1,1]

np.int64(11)

In [ ]:
ar[0:5, 1:2] #get the first column o to 5 row and 1 column  of the array



array([[ 1],
       [11],
       [21],
       [31],
       [41]])

In [94]:
#access  last elemnt of array ]
ar[-1][-1]

np.int64(59)

In [96]:
ar[:4][-1]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [102]:
ar[3,2] =100
ar

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31, 100,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41, 200,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]])

In [107]:
arr_1=np.arange(225)

In [108]:
arr_1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [112]:
arr_1.reshape(5,15,3)

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [113]:
arr_1.reshape(5,15,3)[1, 2, 1]

np.int64(52)

In [126]:
arr_1.reshape(5,15,3)[1, 2, 1] = 10000

In [127]:
arr_1.reshape(5,15,3)[1, 2, 1]

np.int64(10000)

In [128]:
arr_1

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51, 10000,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99,   100,   101,   102,   103,   104,   105,   106,   107,
         108,   109,   110,   111,   112,   113,   114,   115,   116,
         117,   118,   119,   120,   121,   122,   123,   124,   125,
         126,   127,

In [129]:
#multiply  two aray
arr_1 * arr_1


array([        0,         1,         4,         9,        16,        25,
              36,        49,        64,        81,       100,       121,
             144,       169,       196,       225,       256,       289,
             324,       361,       400,       441,       484,       529,
             576,       625,       676,       729,       784,       841,
             900,       961,      1024,      1089,      1156,      1225,
            1296,      1369,      1444,      1521,      1600,      1681,
            1764,      1849,      1936,      2025,      2116,      2209,
            2304,      2401,      2500,      2601, 100000000,      2809,
            2916,      3025,      3136,      3249,      3364,      3481,
            3600,      3721,      3844,      3969,      4096,      4225,
            4356,      4489,      4624,      4761,      4900,      5041,
            5184,      5329,      5476,      5625,      5776,      5929,
            6084,      6241,      6400,      6561, 

In [130]:
arr+2

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33, 102,  35,  36,  37,  38,  39,  40,
        41,  42,  43, 202,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61])

In [131]:
arr-1

array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  99,  32,  33,  34,  35,  36,  37,
        38,  39,  40, 199,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58])

In [133]:
#create list x and y
x = [1, 2, 3, 4, 5]
y = [6, 7, 8, 9, 10]


In [134]:
x+y

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [139]:
#convert list into array
x_arr = np.array(x)
y_arr = np.array(y)
#add two array
x_arr + y_arr
#multiply two array
x_arr * y_arr

array([ 6, 14, 24, 36, 50])

In [140]:
#multiply two array
x_arr * y_arr

array([ 6, 14, 24, 36, 50])